[2021-11-29 12:39:09,398] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-04-12T00:00:00+00:00 [queued]>
[2021-11-29 12:39:09,603] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-04-12T00:00:00+00:00 [queued]>
[2021-11-29 12:39:09,604] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:09,610] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:39:09,618] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:09,737] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-04-12T00:00:00+00:00
[2021-11-29 12:39:09,798] {standard_task_runner.py:52} INFO - Started process 169001 to run task
[2021-11-29 12:39:09,854] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-04-12T00:00:00+00:00', '--job-id', '567', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpm85lpyy5', '--error-file', '/tmp/tmp6zzya1qs']
[2021-11-29 12:39:09,856] {standard_task_runner.py:77} INFO - Job 567: Subtask task_1
[2021-11-29 12:39:10,315] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-04-12T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:39:10,929] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-04-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-12T00:00:00+00:00
[2021-11-29 12:39:10,930] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:39:10,930] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:39:11,098] {subprocess.py:75} INFO - Output:
[2021-11-29 12:39:14,297] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:39:14,769] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200412T000000, start_date=20211129T123909, end_date=20211129T123914
[2021-11-29 12:39:15,312] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:39:15,319] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 169001
[2021-11-29 12:39:15,421] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:39:15,525] {process_utils.py:66} INFO - Process psutil.Process(pid=169001, status='terminated', exitcode=0, started='12:39:09') (169001) terminated with exit code 0
