[2021-11-29 12:30:42,103] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-02T00:00:00+00:00 [queued]>
[2021-11-29 12:30:42,277] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-02T00:00:00+00:00 [queued]>
[2021-11-29 12:30:42,277] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:42,277] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:30:42,278] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:42,371] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-02-02T00:00:00+00:00
[2021-11-29 12:30:42,425] {standard_task_runner.py:52} INFO - Started process 139094 to run task
[2021-11-29 12:30:42,477] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-02-02T00:00:00+00:00', '--job-id', '215', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmprw2ra3xm', '--error-file', '/tmp/tmpqkzartj0']
[2021-11-29 12:30:42,479] {standard_task_runner.py:77} INFO - Job 215: Subtask task_1
[2021-11-29 12:30:43,109] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-02-02T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:30:43,842] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-02-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-02T00:00:00+00:00
[2021-11-29 12:30:43,843] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:30:43,853] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:30:43,921] {subprocess.py:75} INFO - Output:
[2021-11-29 12:30:47,084] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:30:47,448] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200202T000000, start_date=20211129T123042, end_date=20211129T123047
[2021-11-29 12:30:47,793] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:30:47,802] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 139094
[2021-11-29 12:30:47,968] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-29 12:30:47,968] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-11-29 12:30:47,990] {process_utils.py:66} INFO - Process psutil.Process(pid=139094, status='terminated', exitcode=1, started='12:30:41') (139094) terminated with exit code 1
