[2021-11-29 12:17:43,098] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-05T00:00:00+00:00 [queued]>
[2021-11-29 12:17:43,302] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-05T00:00:00+00:00 [queued]>
[2021-11-29 12:17:43,321] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:17:43,322] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:17:43,322] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:17:43,466] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-01-05T00:00:00+00:00
[2021-11-29 12:17:43,514] {standard_task_runner.py:52} INFO - Started process 106272 to run task
[2021-11-29 12:17:43,625] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-01-05T00:00:00+00:00', '--job-id', '26', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmptdhspl5j', '--error-file', '/tmp/tmp2cc2l2pe']
[2021-11-29 12:17:43,637] {standard_task_runner.py:77} INFO - Job 26: Subtask task_1
[2021-11-29 12:17:44,150] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-01-05T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:17:44,942] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-01-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-05T00:00:00+00:00
[2021-11-29 12:17:44,960] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:17:45,007] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:17:45,054] {subprocess.py:75} INFO - Output:
[2021-11-29 12:17:48,176] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:17:48,673] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200105T000000, start_date=20211129T121743, end_date=20211129T121748
[2021-11-29 12:17:49,075] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:17:49,080] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 106272
[2021-11-29 12:17:49,348] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-29 12:17:49,349] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-11-29 12:17:49,370] {process_utils.py:66} INFO - Process psutil.Process(pid=106272, status='terminated', exitcode=1, started='12:17:43') (106272) terminated with exit code 1
