[2021-11-29 12:31:32,699] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-11T00:00:00+00:00 [queued]>
[2021-11-29 12:31:33,100] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-11T00:00:00+00:00 [queued]>
[2021-11-29 12:31:33,122] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:31:33,124] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:31:33,124] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:31:33,290] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-02-11T00:00:00+00:00
[2021-11-29 12:31:33,304] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-02-11T00:00:00+00:00', '--job-id', '254', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpoqcoen5y', '--error-file', '/tmp/tmpe6d499jz']
[2021-11-29 12:31:33,305] {standard_task_runner.py:77} INFO - Job 254: Subtask task_3
[2021-11-29 12:31:33,385] {standard_task_runner.py:52} INFO - Started process 142060 to run task
[2021-11-29 12:31:34,314] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-02-11T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:31:35,060] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-02-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-11T00:00:00+00:00
[2021-11-29 12:31:35,061] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:31:35,062] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:31:35,145] {subprocess.py:75} INFO - Output:
[2021-11-29 12:31:38,208] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:31:38,513] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200211T000000, start_date=20211129T123132, end_date=20211129T123138
[2021-11-29 12:31:38,717] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:31:38,731] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 142060
[2021-11-29 12:31:38,797] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-29 12:31:38,804] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-11-29 12:31:38,877] {process_utils.py:66} INFO - Process psutil.Process(pid=142060, status='terminated', exitcode=1, started='12:31:32') (142060) terminated with exit code 1
