[2021-11-29 12:30:02,636] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-21T00:00:00+00:00 [queued]>
[2021-11-29 12:30:03,135] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2020-01-21T00:00:00+00:00 [queued]>
[2021-11-29 12:30:03,136] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:03,136] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:30:03,136] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:30:03,459] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2020-01-21T00:00:00+00:00
[2021-11-29 12:30:03,644] {standard_task_runner.py:52} INFO - Started process 137204 to run task
[2021-11-29 12:30:04,995] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2020-01-21T00:00:00+00:00', '--job-id', '203', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp90_yb606', '--error-file', '/tmp/tmpq4z8rybo']
[2021-11-29 12:30:05,169] {standard_task_runner.py:77} INFO - Job 203: Subtask task_4
[2021-11-29 12:30:09,119] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2020-01-21T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:30:10,653] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2020-01-21T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-21T00:00:00+00:00
[2021-11-29 12:30:10,660] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:30:10,673] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:30:10,839] {subprocess.py:75} INFO - Output:
[2021-11-29 12:30:14,065] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:30:14,544] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20200121T000000, start_date=20211129T123002, end_date=20211129T123014
[2021-11-29 12:30:15,610] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:30:15,631] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 137204
[2021-11-29 12:30:15,871] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-29 12:30:16,007] {process_utils.py:66} INFO - Process psutil.Process(pid=137204, status='terminated', exitcode=0, started='12:30:03') (137204) terminated with exit code 0
