[2021-11-29 12:34:23,821] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-16T00:00:00+00:00 [queued]>
[2021-11-29 12:34:24,037] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-02-16T00:00:00+00:00 [queued]>
[2021-11-29 12:34:24,051] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:34:24,052] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:34:24,063] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:34:24,186] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-02-16T00:00:00+00:00
[2021-11-29 12:34:24,193] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-02-16T00:00:00+00:00', '--job-id', '358', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpyc0dyo94', '--error-file', '/tmp/tmpfca8t9bt']
[2021-11-29 12:34:24,273] {standard_task_runner.py:52} INFO - Started process 151600 to run task
[2021-11-29 12:34:24,339] {standard_task_runner.py:77} INFO - Job 358: Subtask task_1
[2021-11-29 12:34:24,839] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-02-16T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:34:25,512] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-02-16T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-16T00:00:00+00:00
[2021-11-29 12:34:25,512] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:34:25,513] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:34:25,625] {subprocess.py:75} INFO - Output:
[2021-11-29 12:34:28,762] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:34:29,148] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200216T000000, start_date=20211129T123423, end_date=20211129T123429
[2021-11-29 12:34:29,675] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:34:29,680] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 151600
[2021-11-29 12:34:31,104] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-29 12:34:31,104] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-11-29 12:34:31,117] {process_utils.py:66} INFO - Process psutil.Process(pid=151600, status='terminated', exitcode=1, started='12:34:23') (151600) terminated with exit code 1
