[2021-11-29 12:39:07,514] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-04-11T00:00:00+00:00 [queued]>
[2021-11-29 12:39:07,661] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-04-11T00:00:00+00:00 [queued]>
[2021-11-29 12:39:07,662] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:07,666] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-11-29 12:39:07,667] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-11-29 12:39:07,803] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-04-11T00:00:00+00:00
[2021-11-29 12:39:07,863] {standard_task_runner.py:52} INFO - Started process 168902 to run task
[2021-11-29 12:39:07,897] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-04-11T00:00:00+00:00', '--job-id', '566', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp8z5a39r3', '--error-file', '/tmp/tmpk6r7kpn_']
[2021-11-29 12:39:07,908] {standard_task_runner.py:77} INFO - Job 566: Subtask task_1
[2021-11-29 12:39:08,598] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-04-11T00:00:00+00:00 [running]> on host airflowvm
[2021-11-29 12:39:09,411] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-04-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-11T00:00:00+00:00
[2021-11-29 12:39:09,412] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-11-29 12:39:09,412] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-11-29 12:39:09,556] {subprocess.py:75} INFO - Output:
[2021-11-29 12:39:12,712] {subprocess.py:83} INFO - Command exited with return code 0
[2021-11-29 12:39:13,033] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200411T000000, start_date=20211129T123907, end_date=20211129T123913
[2021-11-29 12:39:13,282] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-11-29 12:39:13,288] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 168902
[2021-11-29 12:39:13,847] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-11-29 12:39:13,847] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-11-29 12:39:13,985] {process_utils.py:66} INFO - Process psutil.Process(pid=168902, status='terminated', exitcode=1, started='12:39:07') (168902) terminated with exit code 1
